### PR TITLE
Remove all unknown or unsupported devices from connect dialog

### PR DESCRIPTION
**Pull request by Olsenius**
Added filter to BLE devices to remove unknown or unsupported devices. Makes it easier to select the right device while connecting.

Screenshot 2020-09-14 at 10 24 16

Screenshot 2020-09-14 at 10 24 49

Added namePrefix A to Z and a to z (and space). This is because i have a hope that some time in the future it will be possible to set name via flasher. 

Tested in Chrome on mac

### CODE REVIEW

**Comment by atc1441** [comment]
Hey,
Thank you

The reason i did not added this feature is because sometimes it takes a lot of time to get the full name so i simply used the MAC to connect to the right one, the name is still null at that state but everything works.

What do you think about that?

**Comment by Olsenius** [comment]
I havent noticed a delay before getting the name, but if that was a problem i understand why you choose to not implement this.
I have 16 unsupported and 7 ATC (and many others) to choose from in my list, so for me this made my life a little better at least :-P

**Comment by Olsenius** [comment]
Another option might be to add a optional input field with name prefix, and use that as a prefix if set. 

With my current workflow i compile with cusom defaults and new name, and then i flash all with the old name. My workflow would be easier with this at least. But i can do my stuff in my own fork :)

**Comment by Olsenius** [comment]
Awesome work with the firmware by the way!

**Comment by atc1441** [comment]
Thank you :)

Also thought about something like an input field or even a checkbox to enable name filtering. 

I would definitely merge that if you write it anyway :)

**Comment by Olsenius** [comment]
Added a checkbox and option to filter as well.

**Comment by atc1441** [comment]
Very nice , thank you :)

i added another new line after the filter to have it more mobile browser friendly

**Comment by Olsenius** [comment]
Perfect. Thanks!

**Pull request merged**
